### ISSUE TITLE
plot_save_graph returning igraph related error: Plotting Not Available

### ISSUE THREAD

**Issue by whitleyo** [KenLauLab/pCreode#1]
Hi,

I'm running pcreode on a linux ubuntu 16.04 VM

I've managed to run pcreode on the sample dataset you've provided, but when I try to plot one of the generated graphs, I get this error:

Traceback (most recent call last):
  File "pcreod_dryrun.py", line 44, in <module>
    overlay= data_raw.ELANE, density=density_1, file_out='Elane', upper_range=1.5)
  File "/usr/local/lib/python2.7/dist-packages/pcreode/functions.py", line 62, in plot_save_graph
    vertex_size=dens, edge_width=2))  
  File "/usr/local/lib/python2.7/dist-packages/igraph/drawing/__init__.py", line 446, in plot
    result = Plot(target, bbox, background=kwds.get("background", "white"))
  File "/usr/local/lib/python2.7/dist-packages/igraph/drawing/__init__.py", line 117, in __init__
    self._surface_was_created = not isinstance(target, cairo.Surface)
  File "/usr/local/lib/python2.7/dist-packages/igraph/drawing/utils.py", line 396, in __getattr__
    raise TypeError("plotting not available")

I'm presuming this has something to do with the Cairo library, since there's a stackoverflow discussion mentioning it regarding a similar error from igraph. If you happen to have an idea as to what's going on, that would be greatly appreciated.

Thanks!

**Comment by whitleyo** [comment]
I also checked and I do have libcairo2 installed

**Comment by herrinca** [comment]
Really sorry for the late response to this, I was not aware an issue was logged. Are you still having the same issue?

**Comment by wyattmcdonnell** [comment]
Hi Chuck, also having the same issue on Mac OS X. On Windows 10 that same routine crashes the Jupyter kernel (running Anaconda 2.7 and followed install instructions to a letter). Thanks!

**Comment by wyattmcdonnell** [comment]
@whitleyo and @herrinca I was able to resolve this on Mac OS X El Capitan, Windows 10, and Ubuntu 16.04 Xenial using a Conda install of iGraph:
```
conda install -c conda-forge python-igraph
```
Everything ran without issue after. Hope this helps!

**Comment by herrinca** [comment]
Thanks for letting us know about your issue! Happy to hear you were able to figure it out.....We have had a lot of issues with igraph plotting. Hopefully this conda install will fix a lot of those issues. I'll update the install functions. Thanks again.

**Comment by herrinca** [comment]
Closing issue
