### ISSUE TITLE
Qualitative MetaData as Overlay for the graph?

### ISSUE THREAD

**Issue by charles-bernard** [KenLauLab/pCreode#2]
Hi,

I was trying your tool today and I worked along with your tutorial without any problem but I had just one question or rather recommendation concerning the graph plot. If I manage to plot the level of expression of my genes of interest along the tree, I was wandering whether you also plan to enable to choose qualitative metadata as overlay for the graph plot?

I understand that several cells can be projected on a node of the tree, so with a quantitative variable (i.e gene expression), it becomes easy to average this variable for all cells of each node, but there are also ways to deal with this with qualitative data.

For instance, you could treat each node as a pie chart or, even simpler, consider only the "majority" value among all the cells composing a node...  

If I'm asking that, it is because I'm trying to do pseudo time analysis and I would like to check how well the ordering of the cells in my p-creode tree matches the labels of my cells. 

That would be great if such options could be implemented

All the best,

Charles

**Comment by herrinca** [comment]
Hey Charles, 

Thanks for the feedback and suggestion! In the version just pushed you can now overlay qualitative data using the plot_save_qual_graph( ) function within the Analysis class. The tutorial has been updated to demonstrate this added function. In the tutorial I use Kmeans clustering as an example, where each node in the graph represents the majority of the data points binned to the node (the most represented cluster ID). I would have preferred to display the nodes as a pie chart but due to igraph's plotting limitations in python that option is not available (which is an option in the R version of igraph). It is  possible to export the graph into a better visualizer like Cytoscape where more options are available. The indices of the cells (in relation to the input data set) binned into each graph node used for dynamic and overlay representations can found in the *_clust_ids.csv file produced using the get_complete_analyte_gene_trajectories() with the same Analysis class.

Chuck

**Comment by charles-bernard** [comment]
Hey Chuck,

Thanks a lot for the update!! 

> Because igraph plotting is the bane of my existence

It made me laugh a lot, especially because I feel the same! Hope it was not too much of a hassle though... 
On the other hand, this new function is great and I'm sure a lot of people will use it. 

 >  It is possible to export the graph

How can I do that, is there a way to export it as a .gml file, so that I can reuse it within R with the igraph package?

> The indices of the cells binned into each graph node can be found in the *clust_ids.csv

Brilliant, along with the exported graph, that's all what is required if I eventually want to make a pie chart plot (really useful if you study for instance differentiation) with R::igraph. BTW, i prefer the new template of this csv file with two rows (one for the cell indexes, the other for the node ids) over the previous one. 

Now, I must admit that I suspect that something is going wrong with this new function when I use it with my own data. Let me be more precise:

I have a normalized dataset in my hands. Prior to my trajectory inference analyses I performed clustering with Seurat. The output is a vector, corresponding to the partition of my cells into 6 clusters. 

Before you responded to my question, and because the plot_save_qual_graph() fct was not available, I decided to turn my partition into quantitative data as follows:

```
             Cell Name Cluster 0 Cluster 1 Cluster 2 Cluster 3 Cluster 4 Cluster 5
   1: AAACCTGCAATCTACG         0         0         0         0         1         0
   2: AAACGGGAGCAGACTG         0         0         0         1         0         0
   3: AAACGGGAGCTGCCCA         0         1         0         0         0         0
   4: AAACGGGGTAGCTAAA         0         0         0         0         0         1
   5: AAAGATGAGAAGGCCT         1         0         0         0         0         0
```
  ­­­   
Then I plotted the pCreode graph with each of the six Clusters column as overlay 
```python
for c in clusters_names:
    analysis.plot_save_graph(seed = seed, overlay = clusters_data[c],
                             file_out = c, upper_range = 2.9)
```

I obtained 6 plots. In each plot, nodes corresponding to the cluster of interest were highlighted. It allowed me to summarize this information as below:

![cluster_manual_annotation](https://user-images.githubusercontent.com/23334620/35730912-1eef026c-0814-11e8-9cff-464ed014ae94.png)

And it was absolutely consistent with another trajectory inference analysis I made with another tool (in development):

![conservative_tree](https://user-images.githubusercontent.com/23334620/35731068-91fd2c20-0814-11e8-8691-e9c7f162c2e6.png)

Nervetheless, when I tested your new function (with a new run)
```python
analysis.plot_save_qual_graph(seed = 0, overlay = partition,
                              file_out="Seurat_Clusters");
```
This is what i obtain:

![legend](https://user-images.githubusercontent.com/23334620/35731321-642604ce-0815-11e8-9c5c-88be37daa333.png)

![seurat_clusters](https://user-images.githubusercontent.com/23334620/35731231-272df964-0815-11e8-8a40-c967b3455d4e.png)

I've checked and of course, the indexes of the cells in my partition are the same as the ones in the data used as input by pcreode... I don't know how to interpret that...

If you perform some clustering before using pcreode and store the partition into a tab file, then reload it inside python, perform the pcreode trajectory inference and then use this partition as overlay, do you observe the same kind of inconsistencies? Maybe there is something wrong with my data but I don't understand why since the indexes of my clusters_tab (quantitative_data) and of my partition vector correspond to the same cells...

Sorry to bother you with this, I just think pCreode is a great tool and I would like therefore to make sure the problem comes indeed from me and not from the package

Best,

Charles

**Comment by charles-bernard** [comment]
Sorry I apologize, there is no mistake. In fact, I obtained something understandable with qualitative data turned into quantitative tab thanks to this parameter : upper_range... which I guess is relative to the values of the variable being plotted and not to the values of all the variables pooled together... In my case, with the node color being set to the most represented clusterID, I lose important information. 

Since igraph in python does not enable pie chart, I was wandering whether it is possible or not to choose myself the number of nodes used for the generation of the graphs (like in Spade for instance) ?

The rational behind this question is the following: the more nodes, the more likely one node = one cluster and not a mixture of clusters

**Comment by herrinca** [comment]
I'm glad it worked out, but I can understand how my overlay is not as informative as the pie charts. I am going to work on another approach to show qualitative data in a more detailed way, but it will likely be less visually appealing than a graph overlay.

You are correct the overlay parameters for quantitative plots only relate to the values associated with a single variable.

Unfortunately, there is not a way to set the number of nodes in a graph. We saw clustering/node number selection as a subjective exercise on continuous data sets that affected the output of the graphs. If the number is too low it increases the likelihood of "shortcuts" (under fitting) and over estimating the number increases the chances that the trajectory tracing will wonder into areas not representative of likeliest pathway and creating superfluous branching (over fitting).

The newest version (I am about to push) contains a new stand alone function that will allow you to produce a weighted adjacency matrix for a selected graph. The tutorial has been updated with an example. Most other graphing library's should take an adjacency matrix as input.

I like the graphs from the new tool you showed. I'll be keeping an eye out for it, looking forward to reading about it....Thanks for all the feedback, let me know if you run into anything else. 

Chuck

**Comment by charles-bernard** [comment]
Alright, thank you so much for your quick and clear responses. I was indeed suspecting that the number of nodes would have an influence on the branching level of the graph (we have the same problem with the tool that is being currently developed in our institute)... And don't worry for the pie chart, if the information can be accessed by another way, that's all what matters in the end. 

Thank you again for all the updates and precisions you gave me, I'm going to close this issue now. 

>  I am going to work on another approach to show qualitative data in a more detailed way

That's great and to this end I've some suggestions, free to you to consider them or not.
To display this information in a very meaningful way, I think of 3 steps:

1) Visualization of the trajectories

Now that you have implemented the plot_save_qual_graph() fct, you can create one output graph by trajectory. For each trajectory, you can create a boolean vector (if the cell is within a node on the trajectory: TRUE, else: FALSE) and use this vector as overlay of the function. This will allow the user to visualize clearly the trajectories

2) Visualization of the pseudotime progression (starting from root node) along the tree

Treat pseudotime as a quantitative vector and use it as overlay for the plot_save_graph(). 
For instance the unit of your x axis (p-Creode Trajectory) in the analyte dynamics plot would be a perfect quantitative vector as overlay

This the kind of information that would be nice to eventually visualize:

![elpigraph_pseudotime](https://user-images.githubusercontent.com/23334620/35766409-6cab9190-08d8-11e8-9e24-2bd0691d582e.png)
 
3) For each trajectory, plot CellLabel (y axis) vs Pseudotime (x axis)

Here is an example I made with slicer

![pseudotime_vs_clusters_in_branch2_](https://user-images.githubusercontent.com/23334620/35766367-5beaaa90-08d7-11e8-9880-dd0b7d2e0542.png)

This way we can see a clear evolution of the cell types along the trajectory being considered

Last but not least, I'm going to "star" your repo ;)

PS: for the tool under development, I'm waiting for it to be published (very soon) since I'm not the main contributor and as soon as it will be, I'll drop you an email

Cheers,

Charles
