### ISSUE TITLE
advice for installation for Mac users

### ISSUE THREAD

**Issue by daskelly** [KenLauLab/pCreode#3]
I have no question but wanted to provide my experience successfully installing on a Mac as I had a few problems initially. I use homebrew and anaconda so I did not want to install using the pure pip method detailed in `README.md`. I installed igraph using `brew install igraph` and installed pCreode as follows:
```bash
git clone git://github.com/KenLauLab/pCreode
cd pCreode
conda create -n pcreode python=2.7 python-dateutil=2.5.3 numpy pandas matplotlib python-igraph jupyter cython
source activate pcreode
pip install .
```
I am running Mac OS v10.13.4. Thanks for developing this software.

**Comment by herrinca** [comment]
Awesome, thanks for the feedback! I have updated the README to include your install.
