### ISSUE TITLE
plot_save_graph returning igraph related error: Plotting Not Available

### ISSUE THREAD

**Issue by sgmccalla** [KenLauLab/pCreode#4]
While running pCreode on macos High Sierra and linux the tutorial works great until the graph plotting step:

analysis.plot_save_graph( seed=seed, overlay=data_raw.A130010J15Rik, file_out='A130010J15Rik', upper_range=1.25)
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-63-79a1fe9af57e> in <module>()
>       1 
> ----> 2 analysis.plot_save_graph( seed=seed, overlay=data_raw.A130010J15Rik, file_out='A130010J15Rik', upper_range=1.25)
> 
> /anaconda3/envs/ipykernel_py2/lib/python2.7/site-packages/pcreode/pcreode.pyc in plot_save_graph(self, seed, overlay, file_out, upper_range, node_label_size)
>     253 
>     254         plot( self.graph, self._file_path + '{0}.png'.format(file_out), layout=layout, bbox=(1200,1200), 
> --> 255                     vertex_size=dens, edge_width=2, vertex_label_size=node_label_size)
>     256 
>     257         display( Image( filename=self._file_path + file_out + '.png', embed=True, unconfined=True, width=600,height=600))
> 
> /anaconda3/envs/ipykernel_py2/lib/python2.7/site-packages/igraph/drawing/__init__.pyc in plot(obj, target, bbox, *args, **kwds)
>     444         bbox = BoundingBox(bbox)
>     445 
> --> 446     result = Plot(target, bbox, background=kwds.get("background", "white"))
>     447 
>     448     if "margin" in kwds:
> 
> /anaconda3/envs/ipykernel_py2/lib/python2.7/site-packages/igraph/drawing/__init__.pyc in __init__(self, target, bbox, palette, background)
>     115         """
>     116         self._filename = None
> --> 117         self._surface_was_created = not isinstance(target, cairo.Surface)
>     118         self._need_tmpfile = False
>     119 
> 
> /anaconda3/envs/ipykernel_py2/lib/python2.7/site-packages/igraph/drawing/utils.pyc in __getattr__(self, _)
>     394 
>     395     def __getattr__(self, _):
> --> 396         raise TypeError("plotting not available")
>     397     def __call__(self, _):
>     398         raise TypeError("plotting not available")
> 
> TypeError: plotting not available
> 

It appears that igraph is installed properly:

> igraph.test.run_tests()
> Ran 307 tests in 12.111s
> OK

I've tried the [previous solution](https://github.com/KenLauLab/pCreode/issues/1) 

> conda install -c conda-forge python-igraph

but it has not solved the issue on either mac or linux. I'm not sure if this might be because I'm already running pCreode from inside a conda environment (conda create -n ipykernel_py2 python=2 ipykernel)? I've also tried uninstalling and re-installing python-igraph.

Thank you!

**Comment by herrinca** [comment]
Thanks for letting us know about your issue. I believe your issue is due to the cairo package not being installed, for some reason this is not seen as a dependency for python-igraph. You can install cairo following these [instructions](http://macappstore.org/cairo/)  or if you have brew you can install using
```
brew install cairo --use-clang 
brew install py2cairo
```
Hopefully, that will take care of your issue.

Chuck

**Comment by sgmccalla** [comment]
Thank you very much, the solution worked!

**Comment by herrinca** [comment]
Great!
