### ISSUE TITLE
TypeError("plotting not available")

### ISSUE THREAD

**Issue by ltongyu** [KenLauLab/pCreode#5]
Hi,

I tried the solutions posted in your issue section-- such as,

conda install -c conda-forge python-igraph
or 

brew install cairo --use-clang 
brew install py2cairo

or

git clone git://github.com/KenLauLab/pCreode
cd pCreode
conda create -n pcreode python=2.7 python-dateutil=2.5.3 numpy pandas matplotlib python-igraph jupyter cython
source activate pcreode
pip install .

But unfortunately  I still kept getting the plotting not available error. 

analysis.plot_save_graph( seed=seed, overlay=data_raw.Alb, file_out='Alb', upper_range=1.25)
Traceback (most recent call last):

  File "<ipython-input-9-1fb184d68fa4>", line 7, in <module>
    analysis.plot_save_graph( seed=seed, overlay=data_raw.Trem2, file_out='Trem2', upper_range=1.25)

  File "/Users/ltongyu/anaconda2/lib/python2.7/site-packages/pcreode/pcreode.py", line 291, in plot_save_graph
    vertex_size=dens, edge_width=2, vertex_label_size=node_label_size)

  File "/Users/ltongyu/anaconda2/lib/python2.7/site-packages/igraph/drawing/__init__.py", line 446, in plot
    result = Plot(target, bbox, background=kwds.get("background", "white"))

  File "/Users/ltongyu/anaconda2/lib/python2.7/site-packages/igraph/drawing/__init__.py", line 117, in __init__
    self._surface_was_created = not isinstance(target, cairo.Surface)

  File "/Users/ltongyu/anaconda2/lib/python2.7/site-packages/igraph/drawing/utils.py", line 396, in __getattr__
    raise TypeError("plotting not available")

TypeError: plotting not available

Do you happen to know how to solve this? Thanks a lot! 
I am using macOS High Sierra 10.13.6.

**Comment by herrinca** [comment]
Hi, sorry to hear you are having some issues. Can you try:

sudo pip install cairocffi

brew uninstall cairo
brew install cairo --use-clang
brew install py2cairo

**Comment by ltongyu** [comment]
Thank you for your advices!

By following sudo pip install cairocffi，I realized I missed some packages: 

distributed 1.21.8 requires msgpack, which is not installed.
grin 1.2.1 requires argparse>=1.1, which is not installed.

After I installed **msgpack** and **argparse** by pip installation and followed your rest of code, it worked for me. Thank you very much!
Tongyu

**Comment by herrinca** [comment]
Great! I'll see about adding those packages to pcreode's package dependency list. Thanks for letting us know about your problem.

**Comment by herrinca** [comment]
Added cairocffi as a dependency for install, going to mark as closed.
