### ISSUE TITLE
Suggestion - provide pCreode releases/versions

### ISSUE THREAD

**Issue by jpcartailler** [KenLauLab/pCreode#6]
Would be nice to have fixed releases of pCreode, so that it's easier to know when an update is available, and also would be nice to have the release notes per version, so that bug fixes and enhancements are obvious. 

I realize that it's more work... so let me know if I can help!

-JP

**Comment by herrinca** [comment]
I think that is a good suggestion, any ideas on a good way to carry that out? I have always worried that users may not notice the upgrades and bug fixes.

**Comment by herrinca** [comment]
Will update/add new tutorials once new features are added.
