### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by roelar** [KenLauLab/pCreode#7]
Hello:
I was using pCreode for analysis of 20-parameters flow cytometry data with very interesting results that may be part of a publication very soon. However, in the mid time, I updated Python from 2.7 to 3 and I found that many parts of your pipeline are not working with the newer version of Python. I was able to find out how to get the basic plots running again, however, I couldn't make the ovelays with "analysis.plot_save_qual_graph" with clusters created by Rphenograph as I was doing with the older version of Python. For some reason I cannot get the right np.array and string matrix with the new version. Are you doing any update to fit pCreode to the new Python version? Hope to be clear enough with my question, given that I am not very experienced in this (super beginner!). Thank you very much,

**Comment by bobchen1701** [comment]
Thanks for the feedback. We are currently in the process of updating p-Creode's compatibility with Python 3, so it's great to see that there's demand for it. If possible, please upload a screen capture or copy-paste the errors that you are getting with analysis.plot_save_qual_graph, np.array, and string matrices.

**Comment by roelar** [comment]
Hello:
Here I attached a file where I detailed the changes that I had to do for running pCreode in Python 3. I am still having some issues with the disappearance of the legend labels in the overlay plots. If you have any comment for solving that it will be very well appreciated. Let me know if the details are clear and if you have better solutions than these. Thank you very much,

--
Romina Elizabeth Araya, Ph.D.
Postdoctoral Visiting Fellow
Inflammatory Cell Dynamics section
Cancer and Inflammation Program
Center of Cancer Research
National Cancer Institute
National Institutes of Health
Building 37 Room 4134
Bethesda, Maryland 20892
Tel. (240) 760-7712

**Comment by roelar** [comment]
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 18 23:34:21 2018

@author: arayare
"""

#1_Change made for being able to import pcreode

sys.path.insert(0, "/Users/arayare/bin/pCreode/pcreode/")
from pcreode import *

#2_Remove “pcreode.” for executing PCA and further functions
data_pca = PCA( data_raw)

#3_For overlay cluster in analysis.plot_save_qual_graph I needed to perform extra transformation of the data in str.
qual_data = data_raw2["ClusterID"]
print (qual_data)
str_qual_data = qual_data.astype( str) 
str_qual_data
#_a_for some reason this is not converting the data to the required string data. The dtype after this is object and a warning message was saying the the format of the str data should be '|S'.
w = str_qual_data.astype ('|S')
w
#_b_in my case I need to transform my string data into a np.array
x = np.array (w)
x
analysis.plot_save_qual_graph( seed=seed, overlay=x, file_out='ClusterID_overlay')

**Comment by roelar** [comment]
Hello:
Here I attached a file where I detailed the changes that I had to do for running pCreode in Python 3. I am still having some issues with the disappearance of the legend labels in the overlay plots. If you have any comment for solving that it will be very well appreciated. Let me know if the details are clear and if you have better solutions than these. Thank you very much,

**Comment by bobchen1701** [comment]
Hi, thank you for the additional information. Some of the issues seem to be stemming from the differences between built-in "str" types of Python 2 vs. Python 3. Here are the updated .py files that you can use to replace those found in your "pCreode/pcreode" directory for re-installation. Given the tutorial Jupyter notebook files provided, these updated .py's should be Python 3 compatible from installation to final output. Please let us know if more compatibility issues arise.

[pcreode.zip](https://github.com/KenLauLab/pCreode/files/2596404/pcreode.zip)

**Comment by roelar** [comment]
Hello:
Thank you for the updated file. I still have the same problem with Python 3. I had to execute the whole pcreode file in Spyder to be able to run the PCA. I tried also with the example data and using Jupyter Notebook and no changes.
Even when running the whole pcreode file makes the PCA work, when I have to run the Density, the following error appears:
 
File "/Users/arayare/pCreode/pcreode/pcreode.py", line 173, in get_density
    all_chunks = get_chunks(range(self._n_pts), chunk_size)

NameError: name 'get_chunks' is not defined

I tried importing manually all the packages that appear in pcreode file, however I couldn't move forward. Do you have any suggestion for this? What do you think my problem is? Thank you very much,

**Comment by bobchen1701** [comment]
Based on your description and the error, it seems like your importing procedure has missed the functions.py file which is necessary for the pipeline to run. We would suggest that you try the following. 

1. Completely uninstall and remove pCreode related files from your system
2. Clone the pCreode repository onto your machine locally
3. Download the "pcreode.zip" file from my previous post and unpack it.
4. Navigate into the cloned directory, the address should be "../pCreode/pcreode/"
5. Replace the __init__.py, pcreode.py, and functions.py found here with the files from step 3
6. Return to "/pCreode/"
7. Use the "sudo pip install . " command to reinstall pCreode (given the updated files in step 5), also ensure that this is installing to the base or virtual environment desired.

**Comment by roelar** [comment]
Hello:
These last instructions worked perfectly. Thank you very much!
