### ISSUE TITLE
read_table vs read_csv

### ISSUE THREAD

**Issue by sandeep13712** [KenLauLab/pCreode#8]
Graph scoring step gives the following future warning :

 adj_1  = pd.read_table( file_path + 'adj_{}.txt'.format( zz), sep=" ", header=None).values
/var/www/provixpre_engine/provixpreEnv/lib/python3.6/site-packages/pcreode/functions.py:488: FutureWarning: read_table is deprecated, use read_csv instead.

It is better to fix the package for this warning to make it more clean.

Thanks,
Sandeep

**Comment by bobchen1701** [comment]
We have replaced all instances of read_table with read_csv.
